const Discord = require("discord.js");

module.exports = {
    name: "swaifu",
    description: "Show waifu of specific name",
    argRequired: true,
    argSize: 1,
    usage: "swaifu Chiaki Nanami",
    async execute(cmdCtx) {
        var message = cmdCtx.message;
        var db = cmdCtx.db;
        var args = cmdCtx.args;

        var waifu;
        var queryName = args[0];

        if (args[1]) {
            queryName += " " + args[1];
        }

        try {
            await db
                .collection("savedWaf")
                .where("name", "==", queryName.toLowerCase())
                .get()
                .then(function (querySnapshot) {
                    querySnapshot.forEach(function (doc) {
                        waifu = doc.data();
                    });
                });
        } catch (error) {
            console.log(error);
            throw error;
        }

        if (waifu) {
            const embed = new Discord.MessageEmbed();

            embed
                .setColor(waifu.color)
                .setTitle(capitalizeFirstLetter(waifu.name))
                .setDescription(
                    "Generated by " + waifu.username + "#" + waifu.discriminator
                )
                .setImage(waifu.url)
                .setFooter("Tallied score: " + waifu.score);

            message.channel.send(embed);
        } else {
            message.channel.send("Something went wrong!");
        }
    },
};

function capitalizeFirstLetter(string) {
    return string
        .split(" ")
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(" ");
}
